version: "1.0.0"

services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    build:
      context: .
      dockerfile: DockerfileOllama
    ports:
      - "11434:11434"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      start_period: 40s
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - app_network
  
  mcpserver:
    container_name: mcpserver
    build:
      context: .
      dockerfile: DockerfileMcp
    ports:
      - "8000:8000"
    networks:
      - app_network
      
  ragapp:
    container_name: ragapp
    build:
      context: .
      dockerfile: DockerfileStreamlit
    ports:
      - "8501:8501"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen3.5:0.8b
    depends_on:
      ollama:
        condition: service_started
      mcpserver:
        condition: service_started
    networks:
      - app_network
  
networks:
  app_network:
    driver: bridge

volumes:
  ollama_models: